// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQ5a2LPNvFsjHPl1qxrxVsmYMkP71yE3w',
    appId: '1:705662914230:web:edcb6b71e61abbb2e62017',
    messagingSenderId: '705662914230',
    projectId: 'plogging-404213',
    authDomain: 'plogging-404213.firebaseapp.com',
    storageBucket: 'plogging-404213.appspot.com',
    measurementId: 'G-3LTKGQ48LM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCh4A8fUs_AkwDM7LyqIQvQCIPGH32XhUY',
    appId: '1:705662914230:android:9027e5c926d895c2e62017',
    messagingSenderId: '705662914230',
    projectId: 'plogging-404213',
    storageBucket: 'plogging-404213.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgUxtM3qO7dZ6-duGTMQ54QXGIj7CWU5M',
    appId: '1:705662914230:ios:b867fa93e2052203e62017',
    messagingSenderId: '705662914230',
    projectId: 'plogging-404213',
    storageBucket: 'plogging-404213.appspot.com',
    iosBundleId: 'com.example.plogging',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgUxtM3qO7dZ6-duGTMQ54QXGIj7CWU5M',
    appId: '1:705662914230:ios:ac5d306206664216e62017',
    messagingSenderId: '705662914230',
    projectId: 'plogging-404213',
    storageBucket: 'plogging-404213.appspot.com',
    iosBundleId: 'com.example.plogging.RunnerTests',
  );
}
